### ISSUE TITLE
Get data for general assistance offices

### ISSUE THREAD

**Issue by elburnett** [OpenMaine/covid19-foodmap#19]
Organizers requested General Assistance office locations. Need to do some research on how to find this dataset.

**Comment by jonjanelle** [comment]
What qualifies as a General Assistance Office?

**Comment by elburnett** [comment]
For the vast majority of cases, it's the same as the Town Office, or the Town Clerk. Larger cities have their own offices. Here's some info, COVID-specific: https://maineequaljustice.org/people/covid-19-resources/general-assistance/

**Comment by jonjanelle** [comment]
That document has some useful resources, but still doesn't have any 'mappable' data that we could integrate. Would it be reasonable to include a section of links to GA resources we know about? 

From the conversations so far it doesn't appear we have a good way to actually collect and input data, so we'll want to be realistic in our communications with MPA/GSFB/CfA about this

**Comment by congdon** [comment]
This was buried in a Slack thread, but step one is checking with the towns' municipal clerks:
https://www.maine.gov/sos/cec/elec/munic.html

I think Em is looking for a volunteer to compile the data, since yes, it's not the same in all municipalities, so we can't just scrape it from someplace.

**Comment by congdon** [comment]
Why was this closed w/o comment? What's happening?

**Comment by justinsteele** [comment]
@congdon I believe it was due to this email sent from Jennie to Jenna and Em. 
<img width="892" alt="Screen Shot 2020-05-04 at 11 29 53 PM" src="https://user-images.githubusercontent.com/1194615/81032843-61149e80-8e5f-11ea-9073-5bd07c19e08a.png">

**Comment by jonjanelle** [comment]
Collecting data to support this does not seem like a feasible task. We might consider adding a section to the pantry site's homepage to inform users about contacting their town halls for GA information, but we are not currently collection or maintaining data.
