### ISSUE TITLE
Need product license 

### ISSUE THREAD

**Issue by elburnett** [OpenMaine/covid19-foodmap#20]
Help determining open source licensing (if any)

**Comment by congdon** [comment]
We should definitely add an OpenSource license to this project. I do not have a strong opinion as to which one, and am likely to think that whatever Scott recommends is good. (Is Scott on our GitHub? I can't 'assign' him.)

**Comment by jonjanelle** [comment]
The GPL 3.0 Affero license Scott suggested (https://www.gnu.org/licenses/agpl-3.0.en.html) seems appropriate. Are others comfortable with this?

**Comment by jonjanelle** [comment]
A license is in place.
