### ISSUE TITLE
Error: Element div not allowed as child of element button in this context.

### ISSUE THREAD

**Issue by BeCitizenSci** [OpenMaine/covid19-foodmap#26]
Error: Element div not allowed as child of element button in this context. (Suppressing further errors from this subtree.)

From line 81, column 21; to line 81, column 46

          <div class="toggle-label">locate

Contexts in which element div may be used:
    Where flow content is expected.
    As a child of a dl element.
Content model for element button:
    Phrasing content, but there must be no interactive content descendant.

**Comment by jonjanelle** [comment]
changed to span
