### ISSUE TITLE
The first child option element of a select element with a required attribute

### ISSUE THREAD

**Issue by BeCitizenSci** [OpenMaine/covid19-foodmap#27]
Error: The first child option element of a select element with a required attribute, and without a multiple attribute, and without a size attribute whose value is greater than 1, must have either an empty value attribute, or must have no text content. Consider either adding a placeholder option label, or adding a size attribute with a value equal to the number of option elements.

From line 88, column 21; to line 88, column 37

          <option value=10>10</op

**Comment by jonjanelle** [comment]
Might warrant discussion. I'd argue that we always want a default selected here and there is no use for an empty option

**Comment by jonjanelle** [comment]
added size attribute
