### ISSUE TITLE
map.html - Consider avoiding viewport values that prevent users from resizing documents.

### ISSUE THREAD

**Issue by BeCitizenSci** [OpenMaine/covid19-foodmap#39]
Consider avoiding viewport values that prevent users from resizing documents.

From line 5, column 3; to line 5, column 111

utf-8">↩  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />↩  <me

**Comment by jonjanelle** [comment]
This is needed to prevent distortion of the map when scaling.
