### ISSUE TITLE
Add SSL certificate to openmaine.org

### ISSUE THREAD

**Issue by jonjanelle** [OpenMaine/covid19-foodmap#42]
Accessing a user's location is not possible in Chrome on in sites that do not have SSL encryption. The JS getCurrentPosition() and watchPosition() functions no longer work on insecure origins.

Investigate adding an SSL certificate (inMotion likely has a paid option. Possible to use Let's Encrypt as a free alternative?) so the site so the site can be accessed via https. Without this, features like 'locate me' cannot be used on openmaine.org

**Comment by elburnett** [comment]
@congdon is this something we should ask CfA about?

**Comment by elburnett** [comment]
They often have some ways to cover these costs, etc

**Comment by congdon** [comment]
CPanel on inMotion indicates that SSL is already in place for our site (and for pantries.openmaine.org). Although yes, it is self-signed.

I'm not 100% clear on the issue... can't we just make everything https? (I'm reading the tech support here: https://www.inmotionhosting.com/support/website/ssl/how-to-force-https-using-the-htaccess-file)

**Comment by congdon** [comment]
FYI that the locate me button does not work for me in any browser as is (Chrome, Firefox, Safari).

(It doesn't seem like important functionality to me... maybe if you're using a phone, I guess?)

**Comment by jonjanelle** [comment]
Something is off about the cert setup.
Trying to access https://openmaine.org via chrome presents a message about an invalid cert for me

**Comment by jonjanelle** [comment]
I'm also going to strong caution against trying to force https until the certificate authority issue is resolved. 

Otherwise Chrome users will see the screen in the attached imaged whenever they try to access an OpenMaine page.

![Invalid_Cert](https://user-images.githubusercontent.com/25403286/80101094-ea160680-853e-11ea-9174-0dbec833dd28.PNG)

**Comment by congdon** [comment]
I wonder if we should take this to DM (in Slack?) and maybe you can help me figure out what we 'should be doing'. I'm totally on board with everything being https on our site. (Makes more sense to me; it just wasn't the 'default' when we set things up.) I will poke around more in cpanel, too.

**Comment by dzwarg** [comment]
Hello,
You will need to acquire a certificate from an external CA (Certificate Authority) -- a self-signed certificate on the openmaine.org site will result in warnings (and block) on all major browsers. I've done this before, and would be happy to assist.

**Comment by jonjanelle** [comment]
Thanks David! Any guidance you could give on this would be appreciated

**Comment by congdon** [comment]
I feel like we should weigh cost/utility here.

A quick/lazy google tells me that it will cost ballpark $250/year to get our domain validated. (Ah, and poking a bit more, maybe just $69 on namecheap, which already has our DNS registry and CfA pays for that. This is just for one subdomain.)

As Em points out, it might be that CfA would pay for this, but it's a big step up from things we've done in the past. OTOH, this project is a big step up from things we've done in the past (and I really think its going to help a lot of people), so maybe this is a nothing and we should just ask CfA to do it and move forward.

On the third hand, we're not processing financial transactions, so we'd be doing this just for the 'locate me' functionality... and is that important?

On the fourth hand, if we're going to ask CfA to cover this, should we go whole hog and ask for the whole site, and not just this subdomain? ($249/year).

**Comment by jonjanelle** [comment]
There may be free options like https://letsencrypt.org/ that we can use. I've used this option on a few sites in the past with success, and it looks like inMotion has an installation guide: https://www.inmotionhosting.com/support/website/ssl/install-lets-encrypt-ssl/. The downside is that we'd need to renew fairly often (every 90 days). 

inMotion also seems to have another free option that might be worth looking into: 
https://www.inmotionhosting.com/support/edu/cpanel/auto-ssl-guide/

I think we'll want to do this for reasons beyond the 'locate me' feature. If users attempt to access the site via https they'll be presented with the "Your connection is not private" message I'd posted above. I suspect for many users this would be enough to disuade them from entering the site at all.

**Comment by congdon** [comment]
Should I just turn that on on inMotion? Any downsides?

(Thanks for the reminder about the warning. I agree.)

**Comment by jonjanelle** [comment]
It could be worth a try (as long as we can turn it off). The description makes it sound adequate for our use cases, although I'm not sure how much we'd need to worry about their warning that the cert may "not have the same level of acceptance" as other options

**Comment by congdon** [comment]
Okay, I turned it on -- FYI that this applies to all of our site. (Which is only good, I think; just noting it.)

"A check for certificates is in progress" from inMotion. I'll edit here when this is done, but I assume this will work fine.

**Comment by jonjanelle** [comment]
It looks like that worked!

**Comment by congdon** [comment]
Yay!

**Comment by jonjanelle** [comment]
InMotion's automatic ssl option is now in use
