### ISSUE TITLE
Usability/accessibility issues

### ISSUE THREAD

**Issue by congdon** [OpenMaine/covid19-foodmap#46]
I am concerned about:
1. Colors and contrast -- e.g., the teal pantry icons don't show up well on the blue-heavy map

2. The font size of the displayed information is super tiny; kind of worse on a phone

**Comment by jonjanelle** [comment]
I will increase the font size before the next release. I'll likely need some input on marker selection, but can gather some options

**Comment by congdon** [comment]
FWIW, It's less of an issue for me once I discovered the 'list' option. But we should still keep an eye on this.

**Comment by dzwarg** [comment]
Hello,
I took some time to resolve some of the color contrast and other accessibility issues. I have been working with the aXe extension, which verifies web content conformance to [WCAG 2.1 AA](https://www.w3.org/TR/WCAG21/).

I will have the code changes submitted in a pull request shortly.
