### ISSUE TITLE
Data cleaning and spreadsheet revisions

### ISSUE THREAD

**Issue by jonjanelle** [OpenMaine/covid19-foodmap#55]
- Add an "Is Active" column to the spreadsheet might deserve priority so we can filter out bad results. Whatever values used need to be consistent (perhaps 'yes'/'no'?). Data validation rules can be setup in the sheet to enforce this.

- Remove the "Covid-19 Hours" column. I think this was confusing to volunteers because most only used 'Covid-19 Days of Week'. All hours entries have been moved into 'Covid-19 Days of Week' already, but the column should still be removed to prevent future issues.

- Some operational/covid-19 notes say things like 'No changes as yet'. These were misused as internal notes and need to be updated to be user-facing. Some notes are also long narratives that should be made more succinct and clear.

**Comment by congdon** [comment]
Wouldn't 'last updated' also be a useful column?

I do not know what "covid-19 days of the week" (or "covid-19 hours") means.

Does it make sense to have two distinct "public notes" and "internal notes" columns? (One for quirky things to be added into the display and the other for something for volunteers to see, but not be part of the map.

**Comment by jonjanelle** [comment]
The covid-19 days of week/hours are being used to hold general info about when a site is open. Renaming this might be a good idea (although I'm not sure what the right name is).

'Date Updated' is currently a column, but its value is missing for a large chunk of entries. Should this be displayed on the map/list when available?

Having 'internal notes' and 'public notes' columns makes sense to me. This naming seems like it'd clarify the intention for editors

**Comment by congdon** [comment]
1. I guess it's not displayed this way, but I guess I don't know why they're "covid hours" instead of just "hours". I think 'hours' is probably fine.

2. I think last updated would be good to be displayed when we have that info... and should possibly be explicitly 'unknown' if we never logged this. It suggests to me that it's stale information and if I were looking for food knowing that it might be out of date seems helpful.

3. Sounds good, with two forms of 'notes'.

**Comment by jonjanelle** [comment]
Could I be given access to make edits to the spreadsheet? I don't have permissions to make column additions or removals, so I can't add the 'Is Active' and 'Internal Notes' columns or remove the superfluous 'Covid-19 Hours' column.

**Comment by jonjanelle** [comment]
A column for internal notes has been added, there is now one one column for 'covid-19 hours', and a column has been added and updated to mark which sites are active. There is still work to be done to determine how we can coordinate with partners for ongoing maintenance, which will be resolved under a different task.
