### ISSUE TITLE
Big Typo on Map Page

### ISSUE THREAD

**Issue by dzwarg** [OpenMaine/covid19-foodmap#56]
I'm not sure what it means to "Seach", but I think our users will know what "Search" means.

![Screen Shot 2020-04-25 at 11 41 29 PM](https://user-images.githubusercontent.com/546151/80297114-6a5e8680-874e-11ea-9b84-5f42b0546c06.png)

**Comment by jonjanelle** [comment]
Fix merged -> https://github.com/OpenMaine/covid19-foodmap/pull/57
