### ISSUE TITLE
Add school pickup data

### ISSUE THREAD

**Issue by elburnett** [OpenMaine/covid19-foodmap#62]

**Comment by jonjanelle** [comment]
Portland Public Schools pickup data has been added to the spreadsheet, but is not yet exposed in the app. Im still fiddling with ways to keep pantries and school pickup data separate while making it obvious that the map can show both

**Comment by jonjanelle** [comment]
@dzwarg and @elburnett : Do you think adding a third category filter for 'School Meal Pickups' is reasonable, or should there be greater separation from pantries?

**Comment by congdon** [comment]
I think a third category sounds like a good idea.

**Comment by jonjanelle** [comment]
Thanks @congdon, I'll start with that approach

**Comment by JohnBrooking** [comment]
FYI, the PPS list is included on the new Wiki "Data Sources" page.

**Comment by jonjanelle** [comment]
School pickup sites have been added as a category
